name: Gitleaks Reusable Scan
on:
  workflow_call:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0 # historial completo para escanear todos los commits
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_LICENSE solo es necesario en cuentas de organizacion, no en personales
