name: Trivy Reusable Scan
on:
  workflow_call:

permissions:
  contents: read

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: '1'
          version: latest
